### ISSUE TITLE
Prefix '/' issue

### ISSUE THREAD

**Issue by vineetkumar19871503** [kapilgp/express-controllers-routes#1]
I have to use '/' with prefix else it won't work. For example : 

expCtrl.bind(router, __dirname + '/src/server/controllers/api', '/api'); //will work

expCtrl.bind(router, __dirname + '/src/server/controllers/api', 'api'); //will not work

In library we can use path.join in the following line:

var ctrlUrl = prefix + '/' + (ctrl.name).trim() + '/';

It will look like this :

var ctrlUrl = path.join('/', prefix, '/', (ctrl.name).trim(), '/');

Let me know if I'm wrong :)

**Comment by kapilgp** [comment]
Hi Vineet,

We can but not with path, it should be like  that:

var ctrlUrl = '/' + prefix + '/' + (ctrl.name).trim() + '/';

:)
